//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CGame.cpp
//  @ Date : 3/29/2017
//  @ Author : 
//
//


#include "CGame.h"

CGame::CGame(CQuiz * quiz, int gameType, int temptLimit) {
	this->gameType = gameType;
	this->temptLimit = temptLimit;
	this->quiz = quiz;
}

int CGame::getGameType() {
	return this->gameType;
}

void CGame::setGameType(int gameType) {
	this->gameType = gameType;
}

int CGame::getTemptLimit() {
	return this->temptLimit;
}

void CGame::setTemptLimit(int temptLimit) {
	this->temptLimit = temptLimit;
}

CQuiz * CGame::getQuiz() {
	return this->quiz;
}

void CGame::setQuiz(CQuiz * quiz) {
	this->quiz = quiz;
}

