//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CQuiz.cpp
//  @ Date : 3/29/2017
//  @ Author : 
//
//


#include "CQuiz.h"
#include "CQuestion.h"

#include <iostream>
#include <string>
#include <msclr\marshal_cppstd.h>
using namespace msclr::interop;

using namespace std;
CQuiz::CQuiz() {
	this->questions = new list<CQuestion>();
}

CQuiz::~CQuiz() {
	if (this->questions != NULL) {
		this->questions->clear();
		delete this->questions;
		this->questions = NULL;
	}
}

CQuiz::CQuiz(CQuiz *quiz) {
	this->questions = new list<CQuestion>();

	if (quiz != NULL) {
		for (int i = 0; i < quiz->getNumOfQuestions(); i++) {
			this->questions->push_back(quiz->getQuestion(i));
		}
	}
}

int CQuiz::getNumOfQuestions() {
	if (this->questions != NULL)
		return this->questions->size();
	else
		return 0;
}

CQuestion CQuiz::getQuestion(int index) {
	if (this->questions == NULL || index < 0 || index >= this->questions->size())
		return NULL;

	int count = 0;
	for (list<CQuestion>::iterator it = this->questions->begin();
		it != this->questions->end(); it++) {
		if (count == index) return *it;
		count++;
	}
}

void CQuiz::addQuestion(CQuestion question) {
	if (this->questions == NULL)
		this->questions = new list<CQuestion>();

	this->questions->push_back(question);
}

void CQuiz::removeQuestion(int index) {
	if (this->questions != NULL)
		this->questions->pop_back();
}

void CQuiz::updateQuestion(int index, CQuestion question) {
	if (this->questions == NULL || index < 0 || index >= this->questions->size())
		return ;

	int count = 0;
	for (list<CQuestion>::iterator it = this->questions->begin();
		it != this->questions->end(); it++) {
		if (count == index) {
			*it = question;
			return;
		}
		count++;
	}
}

string CQuiz::getTitle() {
	return this->title;
}

void CQuiz::setTitle(string title) {
	this->title = title;
}
string CQuiz::toString() {
	return "Title: " + this->getTitle() + "\nNumber of questions: "
		+ std::to_string(this->getNumOfQuestions()) + "\n";
}

