//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CStudent.cpp
//  @ Date : 3/29/2017
//  @ Author : 
//
//


#include "Student.h"
#include "ContactInfo.h"

string CStudent::getName() {
	return this->name;
}

void CStudent::setName(string name) {
	this->name = name;
}

string CStudent::getID() {
	return this->ID;
}

void CStudent::setID(string ID) {
	this->ID = ID;
}

CContactInfo CStudent::getContact() {
	return this->contactInfo;
}

void CStudent::setContact(CContactInfo contact) {
	this->contactInfo = contact;
}

CStudent::CStudent(string name, string ID) {
	this->name = name;
	this->ID = ID;
}

CStudent::CStudent(string name, string ID, string address,
	string email, string phone) {
	CStudent(name, ID);
	this->contactInfo.setAddress(address);
	this->contactInfo.setEmail(email);
	this->contactInfo.setPhone(phone);

}
string CStudent::toString() {
	return "Name: " + this->name + "\nID: " + this->ID + "\n";
}

string CStudent::getFullInfor() {
	return toString();
}

